# Requires repo secret: PERSONAL_ACCESS_TOKEN with permissions:
#   Contents: read and write
#   Pull Requests: read and write

name: Update Formula

on:
  schedule:
    # Every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install homebrew-npm-noob

      # Update the formula and commit to the default branch
      - id: update-and-commit
        run: |
          noob igir > Formula/igir.rb
          git add --all

          USER_EMAIL="${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          echo "USER_EMAIL=${USER_EMAIL}" >> "${GITHUB_OUTPUT}"
          git config --global user.email "${USER_EMAIL}"

          USER_NAME="$(gh api "/users/${GITHUB_ACTOR}" | jq .name -r)"
          echo "USER_NAME=${USER_NAME}" >> "${GITHUB_OUTPUT}"
          git config --global user.name "${USER_NAME}"

          PACKAGE_VERSION=$(npm show igir --json | jq --raw-output '.version')
          git commit -m "v${PACKAGE_VERSION}" || exit 0
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}
      
      # Create the pull request, and mark it as auto-merge
      - if: ${{ steps.update-and-commit.outputs.PACKAGE_VERSION }}
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          author: ${{ steps.update-and-commit.outputs.USER_NAME }} <${{ steps.update-and-commit.outputs.USER_EMAIL }}>
          branch: ${{ github.actor }}/${{ steps.update-and-commit.outputs.PACKAGE_VERSION }}
          delete-branch: true
          title: v${{ steps.update-and-commit.outputs.PACKAGE_VERSION }}
      - if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: |
          {
            echo "# v${{ steps.update-and-commit.outputs.PACKAGE_VERSION }}"
            echo ""
            echo "${{ steps.create-pull-request.outputs.pull-request-url }}"
          } >> "${GITHUB_STEP_SUMMARY}"
      - if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: gh pr merge "${{ steps.create-pull-request.outputs.pull-request-number }}" --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
